### ISSUE TITLE
All APIs need to be revisited to make sure constants and read-only fields are implemented correctly

### ISSUE THREAD

**Issue by rwmtse** [blackberry-webworks/BB10-Webworks-API#13]
Fields defined using defineGetter are not read-only under the BB10 WebWorks architecture.

Read-only field must be defined using the following way:

``` javascript
Object.defineProperty(obj, "prop", {
    value: webworks.execSync(feature, "prop", args),
    writable: false
});  
```

Refer to blackberry.app API.

**Comment by rwmtse** [comment]
The define read-only property code should be refactored into a common util method so that all API uses the same way to define read-only properties.

**Comment by nukulb** [comment]
@kwallis  - this does not feel like a high priority bug, am I missing anything?
properties still seem available, if someone changes it well too bad, I think this can be downgraded.

**Comment by kwallis** [comment]
I'll admit I was unsure of the full scope of this, though the description indicated that we weren't sure everything was working "correctly".

## I do worry about the potential, accidental or intentional by the dev, to screw up the behaviour of their app because they modified a read-only field.  It could be a P2 though for post Beta 1

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-WebWorks-Framework#12
