### ISSUE TITLE
Browser cannot be invoked in SCM 1.0.0 bundle 3

### ISSUE THREAD

**Issue by erhorim** [blackberry-webworks/BB10-Webworks-API#19]
Description:
In an app that invokes browser with the following API:

var args = new blackberry.invoke.BrowserArguments("www.rim.com");
blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, args);

In device with jnext workaround, browser cannot be invoked.

Build: BlackBerry Webworks SDK for BB10 1.0.0 Bundle 3

**Comment by nukulb** [comment]
So it seems like the reason why the browser cannot be invoked is because there is lock on the pps file and we cannot write to PPS, it just returns false.
the minimal test for the invoke currently does this -

```

               function invokeBrowser ()
                     var pps = new JNEXT.PPS(),
                     ctrlObj = {
                      'id': "",
                      'dat': 'http://www.rim.com',
                      'msg': "invoke"
                  };
                };
                pps.init();
                pps.open('/pps/services/navigator/control?server',2);
                pps.write(ctrlObj);
                pps.close();
            }

```

I am not sure how this ever worked, it seems like it should have never worked.

The correct code should be using the 
 chrome.internal.navigator.onInvoke and passing in the URL.

@jeffheifetz - please modify your minimal test and try this new code out - you can refer to https://github.com/blackberry-webworks/BB10-WebWorks-Framework/pull/16 to find out how @rwmtse uses chrome.internal.navigator. If you can try this asap, it would really help resolve this asap.

@adrianlee/ @rwmtse - if you get a chance you try this as well, it will help resolve this before Monday's build

**Comment by rwmtse** [comment]
OnInvoke is not used to be used for invoking other apps like browser, oninvoke is for some other app to invoke the webworks app.

----- Original Message -----

**Comment by nukulb** [comment]
I see, sorry my bad. So then we something in the webplatform to allow us to invoke an app?

**Comment by rwmtse** [comment]
I guess so, if we are no longer allowed to send message to navigator directly

----- Original Message -----

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-WebWorks-Framework#19
