### ISSUE TITLE
As a WebWorks developer, I can access an un-sandboxed file system

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#33]
### Acceptance Criteria
- The developer can set a property _blackberry.io.sandbox_ to true or false.
- _blackberry.io_ will be used for whitelisting.
- If this flag is set to true which is the default, then the file system will be sandboxed, and requestFileSystem will respect the window.TEMPORARY and window.PERSISTENT flags to return the appropriate application sandbox locations.
- When the file system is un-sandboxed by setting _blackberry.io.sandbox_ to false, requestFileSystem will always return a file system that is rooted at "/"
- The developer can use a constant _blackberry.io.sharedFolder_ to reference the shared folder.
  - For an application installed in the consumer perimeter, this should point to _/accounts/1000/shared/_
  - For an application installed in the enterprise perimeter, this should point to _/accounts/1000-enterprise/shared/_
- Need to add a constant _blackberry.io.SDCard_ that developers can use to reference the SDCard, and it should point to _/accounts/1000/removable/sdcard/_
- Need to add a constant _blackberry.io.home_ that developers can use to reference the home directory for the application itself, and it should point to _TO BE CONFIRMED_
- Ensure we emulate this in Ripple as well (https://github.com/blackberry/Ripple-UI/issues/375)

**Comment by nukulb** [comment]
@kwallis - Modify the user story to reflect

We no longer need to read the permission 
INSTEAD -
We need to overwrite the requestFileSystem to provide an extra option so that someone can do this -

```
window.requestFileSystem(blackberry.config.BLACKBERRY_ROOT, 1024*1024, onInitFs, errorHandler);
```

@rwmtse -
Lets discuss how I think we should be able to do this-

I prototyped this - We need to do this on the client side. We can do it in the webworks.js before we fire webworks ready or we can possibly do it with a execute JavaScript call.

```

    var oldFs = window.webkitRequestFileSystem;
    window.webkitRequestFileSystem = function () {

        if (Array().slice.call(arguments)[0] === 3) {
           Array().slice.call(arguments)[0] = window.TEMPORARY;
           window.webworks.execSync("blackberry.app", "sandbox", {"sandbox": false});//temporary
           arguments[0] = window.TEMPORARY;
        } else {
           window.webworks.execSync("blackberry.app", "sandbox", {"sandbox": true});//temporary
        }
        oldFs.apply(window, arguments);   
    }
```

On the server side I added this I just added a blackberry.app.sandbox - You can look at the patch. You can apply the patch to the next branch. We should find a more hidden place to put the blackberry.app.sandbox, we will chat tomorrow morning.

For the HOME we should be able to get -

```
window.qnx.webplatform.getApplication().getEnv("HOME")
```

For distinguishing between Enterprise and consumer perimeter we can use the HOME environment variable because that is
actually different for the enterprise perimeter vs. consumer perimeter
Go thread to read-
http://foundry51.qnx.com/sf/go/topc21754

**Comment by nukulb** [comment]
[patch.txt](https://github.com/downloads/blackberry-webworks/BB10-Webworks-API/patch.txt)

**Comment by nukulb** [comment]
similarly requestFileSystemSync should also be overwritten

All this is still pending if we decide to go down this path.

The other option is to simply provide an API.

**Comment by kwallis** [comment]
User story updated to reflect latest design.
