### ISSUE TITLE
As a WebWorks developer, I have access to virtual keyboard events

### ISSUE THREAD

**Issue by nukulb** [blackberry-webworks/BB10-Webworks-API#34]
### Acceptance Criteria
- As a developer, I should be able to react to the fact that the virtual keyboard is displayed, or closed.
- Developer can add/remove the following events with the typical event syntax of _blackberry.event.addEventListener("<eventname>", onEvent);_
  - _onKeyboardOpening_
  - _onKeyboardClosing_
  - _onKeyboardOpened_
  - _onKeyboardClosed_
  - _onKeyboardPosition_
    NEED TO finalize what the data is that comes with each event.
- _blackberry.app_ will be used for the namespace and whitelisting for these events.

**Comment by jeffheifetz** [comment]
The events do not appear to have any data except onKeyboardPosition which has the yPosition

**Comment by adrianlee** [comment]
@kwallis 

I currently have these keyboard events implemented under `blackberry.app` along with swipedown, pause and resume events. I spoke with @nukulb and we both agree keyboard events should be under `blackberry.app` instead of `blackberry.system`.

The browser also uses has these events under the application.namespace. i.e.
- application.keyboardOpening
- application.keyboardOpened
- application.keyboardClosing
- application.keyboardClosed
- application.keyboardPosition

**Comment by nukulb** [comment]
@kwallis -  I believe you suggested blackberry.app namespace at first and then we decided that system is better, after talking with Adrian I think app namespace makes more sense. Are you ok ith this?
If yes we should update the ripple user story and the low memory user story

**Comment by kwallis** [comment]
## I am fine with that.

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by kwallis** [comment]
Updated to reflect app namespace
