### ISSUE TITLE
As a WebWorks developer, I can retrieve a unique identifier for the device

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#9]
The developer should be able to retrieve a unique identifier for the device.

Acceptance Criteria
1. The device unique identifier (eg. PIN) is stored in the following property:
   - blackberry.identity.uuid
2. "blackberry.identity" will be used as the feature id for whitelisting.

**Comment by rwmtse** [comment]
@kwallis Just want to double-check the expected behavior for this user story. In order to read the PIN, the user must specify read_device_identifying_information permission in config.xml (that has always been the case for blackberry.identity API, see https://bdsc.webapps.blackberry.com/html5/apis/blackberry.identity.html)

If the user doesn't specify the permission, the server side code cannot read the PPS object. My current implementation is to give back an empty string for blackberry.identity.uuid

Is this a proper way to handle it?

**Comment by kwallis** [comment]
## What is the current behaviour on PlayBook?

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by rwmtse** [comment]
Got SV&V to try it. On Playbook, if the permission is not specified blackberry.identity.PIN is null.

**Comment by kwallis** [comment]
## Let's stick with that.

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by ishneur** [comment]
SV&V testing passed on Windows.

**Comment by erhorim** [comment]
Feature implemented by blackberry-webworks/BB10-WebWorks-Framework#4
